name: 定时提醒周报任务

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:
  schedule:
    # 可自定义 cron 表达式
    - cron: '30 1,2 * * 4'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: hf-zhu/v2ex-action@main
        with:
          webhook: ${{ secrets.WEBHOOK }}
          secret: ${{ secrets.SECRET }}
          count: 1
